apache_package_name: apache2
apache_service: apache2
php_package_name: libapache2-mod-php
ssh_users: 'joan simone'
ssh_template_file: sshd_config_ubuntu.j2

ifconfig: net-tools
tree: tree
curl: curl
wget: wget
git: git
htop: htop
neofetch: neofetch
